/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicUploadCatalogImageRouteImport } from './routes/api/public/upload-catalog-image'
import { Route as ApiPublicCatalogImageSplatRouteImport } from './routes/api/public/catalog-image/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicUploadCatalogImageRoute =
  ApiPublicUploadCatalogImageRouteImport.update({
    id: '/api/public/upload-catalog-image',
    path: '/api/public/upload-catalog-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCatalogImageSplatRoute =
  ApiPublicCatalogImageSplatRouteImport.update({
    id: '/api/public/catalog-image/$',
    path: '/api/public/catalog-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/upload-catalog-image': typeof ApiPublicUploadCatalogImageRoute
  '/api/public/catalog-image/$': typeof ApiPublicCatalogImageSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/upload-catalog-image': typeof ApiPublicUploadCatalogImageRoute
  '/api/public/catalog-image/$': typeof ApiPublicCatalogImageSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/upload-catalog-image': typeof ApiPublicUploadCatalogImageRoute
  '/api/public/catalog-image/$': typeof ApiPublicCatalogImageSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/api/public/upload-catalog-image' | '/api/public/catalog-image/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/upload-catalog-image' | '/api/public/catalog-image/$'
  id:
    | '__root__'
    | '/'
    | '/api/public/upload-catalog-image'
    | '/api/public/catalog-image/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicUploadCatalogImageRoute: typeof ApiPublicUploadCatalogImageRoute
  ApiPublicCatalogImageSplatRoute: typeof ApiPublicCatalogImageSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/upload-catalog-image': {
      id: '/api/public/upload-catalog-image'
      path: '/api/public/upload-catalog-image'
      fullPath: '/api/public/upload-catalog-image'
      preLoaderRoute: typeof ApiPublicUploadCatalogImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/catalog-image/$': {
      id: '/api/public/catalog-image/$'
      path: '/api/public/catalog-image/$'
      fullPath: '/api/public/catalog-image/$'
      preLoaderRoute: typeof ApiPublicCatalogImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicUploadCatalogImageRoute: ApiPublicUploadCatalogImageRoute,
  ApiPublicCatalogImageSplatRoute: ApiPublicCatalogImageSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
